// <auto-generated />
using CIS174.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CIS174.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CIS174.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("grade")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            FirstName = "Michelle",
                            LastName = "Alexander",
                            grade = 23
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Stephen E.",
                            LastName = "Ambrose",
                            grade = 32
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Margaret",
                            LastName = "Atwood",
                            grade = 36
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Jane",
                            LastName = "Austen",
                            grade = 34
                        },
                        new
                        {
                            StudentId = 5,
                            FirstName = "James",
                            LastName = "Baldwin",
                            grade = 21
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
